FROM oven/bun:1.3 AS base
WORKDIR /app

# Install dependencies
COPY package.json bun.lock turbo.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/
RUN bun install

# Build shared package
COPY packages/shared ./packages/shared
RUN cd packages/shared && bun run build

# Build web app
COPY apps/web ./apps/web
RUN cd apps/web && bunx prisma generate && bun run build

WORKDIR /app/apps/web
ENV NODE_ENV=production
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["bun", "server.ts"]
